name: Test Theme
on:
    - push
    - pull_request
jobs:
    test:
        runs-on: ubuntu-22.04
        steps:
            -   uses: actions/checkout@v2
            -   name: Install Node.js
                uses: actions/setup-node@v3
                with:
                    node-version: ^18

            -   name: Install PNPM
                id: pnpm-install
                uses: pnpm/action-setup@v2
                with:
                    version: ^7.29
                    run_install: false

            -   name: Get pnpm store directory
                id: pnpm-cache
                shell: bash
                run: |
                    echo "STORE_PATH=$(pnpm store path)" >> $GITHUB_OUTPUT

            -   uses: actions/cache@v3
                name: Setup pnpm cache
                with:
                    path: ${{ steps.pnpm-cache.outputs.STORE_PATH }}
                    key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
                    restore-keys: |
                        ${{ runner.os }}-pnpm-store-

            -   name: Install dependencies
                run: pnpm install

            -   name: Test theme
                run: pnpm test
